trigger:
  branches:
    include:
      - main
      - dev
      - feature/*
      - release/*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: NodeJS
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'

  - script: |
      npm test
    displayName: 'npm test'
